server:
  port: ${CONTENT_SERVICE_SERVER_PORT:8082}

management: #actuator configuration
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:  #for zipkin logging
    sampling:
      probability: 1.0
