server:
  port: 8088

spring:  #config server configuration
  application:
    name: post-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkatram64/k8s-ms-cntralized-config.git
          search-paths:   # Correct for your directory structure
            - config/content-service
            - config/post-service
            - config/post-api-gateway-service
            - config/service-registry-in-eureka
            - config                       # Fallback to config directory
            - .                           # Repository root (for application.yml)
          clone-on-start: true   # Ensures config is pulled on startup
          default-label: main    # Default git branch
          force-pull: true       # Recommended to get latest changes

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: TRACE
