spring:
  config:
    activate:
      on-profiles: dev
    import: "configserver:http://post-config-server:8088"
  zipkin:
    base-url: http://zipkin-server:9411
    enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:post-mysql}:3306/db_posts_new
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 15000
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 50000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always

eureka:
  client:
    register-with-eureka: true  # Changed from registerWithEureka (camelCase to kebab-case)
    fetch-registry: true        # Changed from fetchRegistry
    service-url:               # Changed from serviceUrl
      default-zone: http://service-registry-in-eureka:8761/eureka/  # Changed from defaultZone
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false   # Changed from preferIpAddress
    hostname: ${EUREKA_INSTANCE_HOSTNAME:post-service}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}  # Changed from instanceId
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30