
spring:
  application:
    name: post-service
  config:
    activate:
      on-profiles: local
#  config:
#    activate:
#      on-profile: local
#    import: "optional:configserver:http://localhost:8088"
  zipkin:
    base-url: http://zipkin-server:9411
    enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_posts_new
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #database connection pool configuration
      connection-timeout: 15000
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 50000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always

eureka:  #client is registering into Eureka server
  client:
    register-with-eureka: true  # Changed from registerWithEureka (camelCase to kebab-case)
    fetch-registry: true        # Changed from fetchRegistry
    service-url: # Changed from serviceUrl
      defaultZone: http://localhost:8761/eureka/
  instance:
    #preferIpAddress: true
    #hostname: localhost
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}

