

eureka:
  instance:
    hostname: service-registry-in-eureka
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    wait-time-in-ms-when-sync-empty: 0
