
spring:
  application:
    name: service-registry-in-eureka
eureka:
  instance:
    hostname: service-registry-in-eureka  # Must match Kubernetes service name
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # Add these new properties
    prefer-same-zone-eureka: true
    availability-zones:
      default: default
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    # Add peer node configuration
    peer-node-connect-timeout-ms: 1000
    peer-node-read-timeout-ms: 1000
    peer-node-total-connections: 10
